### ISSUE TITLE
Write a medium article about jest builder

### ISSUE THREAD

**Issue by jogelin** [angular-builders/jest#5]
I just see new a article [Integrate Jest into an Angular application and library](https://blog.angularindepth.com/integrate-jest-into-an-angular-application-and-library-163b01d977ce).

Now you need to communicate about your builder, a lot of person will like it ;)

**Comment by meltedspark** [comment]
It is in progress :) I just need to stabilize it first.

**Comment by cgatian** [comment]
This is LEGIT

**Comment by meltedspark** [comment]
This issue was moved to meltedspark/angular-builders#21
