### ISSUE TITLE
configure code coverage from project root

### ISSUE THREAD

**Issue by cgatian** [angular-builders/jest#7]
Default configuration could specify a `collectCoverageFrom` property with some Angular defaults.

Perhaps expose a new option that would default coverage collection from all TypeScript files within the target project root.

Example:
```
  "collectCoverageFrom": [
    "**/src/**/*.ts",
    "!**/index.ts",
    "!**/public_api.ts",
    "!**/node_modules/**",
    "!**/vendor/**",
    "!**/*.module.ts",
    "!**/src/environments/*.ts",
    "!**/src/main.ts","!**/src/polyfills.ts","!**/src/test.ts",
    "!**/e2e/src/app.e2e-spec.ts","!**/e2e/src/app.po.ts"
],
```

**Comment by meltedspark** [comment]
I'm not sure I understand the request. Are you talking about multi-project workspace? 
You can still specify this option in `jest.config.js` and provide it as a custom configuration.

**Comment by jogelin** [comment]
@cgatian I think these configurations should be added in the default configuration but not in this library but in the https://github.com/thymikee/jest-preset-angular because this builder is using it

**Comment by cgatian** [comment]
I understand the configuration _could_ be supplied there but when you run code coverage you only want coverage across the **project** you are running unit tests against. The builder knows the project root being built and can provide specific configuration to Jest. If the present supplied this it would have to glob all files in the workspace root (not the project).

Remember workspaces can contain multiple projects, and you dont want to collect coverage from all when you may only be targeting unit tests for a specific project.

**Comment by jogelin** [comment]
@cgatian Indeed, I agree ! I think, the goal of the builder is to apply the common configs in each project but the common configs are provided by the angular presets library...

**Comment by cgatian** [comment]
They are, but thats not to say you could build off the common config.

By specifying a new option on the builder the `collectCoverageFrom` option in Jest could be dynamically configured. Something that's not possible within the `angular-preset-jest` library since its static configuration. The builder has knowledge of the files it will run against.

**Comment by cgatian** [comment]
Yes I believe that would work.  I was unaware the configs stack and are located per project.
